# -------------------------------------------------------------
#  definir puerto principal
# -------------------------------------------------------------

server:
  port: 8080

# -------------------------------------------------------------
#  conexion con la base de datos local con liquibase MYsql
# -------------------------------------------------------------

spring:
  application:
    name: gestion-hospitalaria
  liquibase:
    enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/db_gestionhospital?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# -------------------------------------------------------------
#  coneccion con eureka (prender primero eureka antes que este proyecto)
# -------------------------------------------------------------

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# -------------------------------------------------------------
#  configurar swwager
# -------------------------------------------------------------

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# -------------------------------------------------------------
#  puertos de los microservicios
# -------------------------------------------------------------

#especialidad

---
spring:
  config:
    activate:
      on-profile: especialidad
  application:
    name: especialidades
server:
  port: 8081

#Medico

---
spring:
  config:
    activate:
      on-profile: medico
  application:
    name: medico

  cloud:
    gateway:
      routes:
        - id: ruta-medicos-gateway
          uri: http://localhost:8080
          predicates:
            - Path=/api/medicos/**
server:
  port: 8082
